spring:

  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

  redis:
    host: 8.130.19.151
    port: 16379
    database: 3
    password: rIj12YF23S

server:
  port: 7777


#logging:
#  level:
#logging:
#  level:
#    org.springframework.cloud.openfeign: trace
#    reactor: trace
#    org.springframework.cloud.gateway: debug