spring:

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

  redis:
    host: 8.130.19.151
    port: 16379
    database: 6
    password: rIj12YF23S

  application:
    name: aigc-service

server:
  port: 13131

chat:
  config:
    analyse-text:
      preset: |
        你是一个计算机领域专家,能够分析我给出的文章的主要内容并生成其摘要和标签.
        其中摘要应该尽量精简并体现文章的特点,标签形如'spring/mybatis/事务'这样以计算机领域技术专有名词加'/'区分的形式,标签数量不宜过多，应该体现主要内容.
        你的回答应该分为两行:第一行是摘要,第二行是标签,并以'$$'分隔。示例:
        '本文介绍了如何使用SpringBoot整合Redis，并给出了相关配置和代码示例，以及推荐了使用RedisDesktopManager作为图形界面工具进行数据访问。$$SpringBoot2/Redis/配置/代码示例/数据访问/RedisDesktopManager.'
      prompt: 文章标题:%s\n文章内容:%s
      separator: $$

    detect-text:
      preset: |
        你是一个文本敏感内容检测助手，能够分析我给出的文本中是否包含暴力/恐怖/色情/歧视/政治/侵权/广告/诈骗/宗教等元素，并给我反馈:
        当包含以上内容时你应该回复1，否则回复0,请记住你的回答只能是0或1，不要包含其他内容
      prompt: 文章标题:%s\n文章内容:%s
      reply: 0

    recommend-user-profile:
      preset: |
        你是一个用户画像分析助手，能够根据我给你提供的用户职业/偏好/偏好的文章来分析用户的技术水平、行业背景、用户偏好文章特点，并用$$分隔这些内容。你的回答示例:
        '技术水平:高级水平:在特定技术领域有深入研究和实践经验，并能够解决复杂的技术问题。$$
        行业背景:电子商务：在电子商务行业从事网站开发和电子支付系统的设计与实施。$$
        偏好文章:用户喜欢阅读与后端开发相关的文章，特别是与springboot和elasticsearch相关的文章。用户对于缓存优化、虚拟机连接、ES索引的生成和ES复杂搜索等主题很感兴趣。用户可能对于提升后端性能、优化开发环境、掌握主流的后端技术有较高的关注度。'
      prompt: |
        用户职业: %s
        用户偏好: %s
        用户近期喜欢的文章: %s
        用户近期搜索历史: %s
      separator: $$

    recommend-candidate-article:
      preset: |
        你是一个文章推荐助手，能够用户画像以及用户提示推测用户可能喜欢的文章的标题，请为我推荐三篇文章。
        你的回答应该只包含3个文章标题，并以$$分隔，除此之外不要包含任何信息，示例：深入浅出线性回归算法$$从头开始构建一个代码评测系统$$Web开发中的后端与前端通信方式
      prompt: |
        用户画像:%s
        用户提示:%s
      separator: $$

    recommend-select-article:
      preset: 你是一个文章推荐助手，能够根据我提供的用户画像在候选文章中选出用户最可能喜欢的文章，你的回答只需要包含这些文章的编号,以','分隔，示例:3,9,12
      prompt: |
        用户画像:%s
        用户提示:%s
        候选文章:%s
      separator: ,

    question-helper:
      preset: 你是一个算法题助手，能够根据我提供给你的问题描述/用户代码/错误信息/实际执行结果/正确结果,综合分析出用户的代码存在的问题，并给用户提出建议。
      prompt: