spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_white_box
    username: root
    password: 1234

  data:
    redis:
      host: 192.168.99.2
      port: 6379
      password: kaisa666
      database: 0

server:
  port: 8081
mybatis:
  type-aliases-package: com.caesar.model.entity
  mapper-locations: classpath:static/mappsers/*.xml
  configuration:
    map-underscore-to-camel-case: true