spring:
  application:
    name: question-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_white_box
    username: root
    password: 1234

  data:
    redis:
      host: 127.0.0.1
      port: 6666
      database: 0

server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18888/eureka

rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    topic: execute
    group: question-service
