spring:
  application:
    name: question-service

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        import-check:
#          enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_white_box
    username: root
    password: 1234

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

server:
  port: 10098

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:18888/eureka

rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    topic: execute
    group: question-service
