spring:
  application:
    name: question-service

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        import-check:
#          enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.19.151:13306/db_white_box
    username: root
    password: 5eqPGg62I4

  redis:
    host: 8.130.19.151
    port: 16379
    database: 2
    password: rIj12YF23S

server:
  port: 10098

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:18888/eureka

rocketmq:
  name-server: 8.130.26.7:9876
  consumer:
    topic: execute-code-resp
  producer:
    group: question-service
    topic: execute-code
#    group: question-service
