spring:
  application:
    name: executor-service

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848
  redis:
    host: 8.130.19.151
    port: 16379
    database: 4
    password: rIj12YF23S

server:
  port: 6789

rocketmq:
  name-server: 8.130.26.7:9876
  consumer:
    topic: execute-code

  producer:
    group: executor-service
    topic: execute-code-resp

sandbox:
  java:
    dir: "javaCode"
    compile-cmd: "javac -encoding utf-8 %s"
    run-cmd: "java -Dfile.encoding=UTF-8 -cp %s Main"