spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.19.151:13306/db_white_box
    username: root
    password: 5eqPGg62I4

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

  redis:
    host: 8.130.19.151
    port: 16379
    database: 5
    password: rIj12YF23S

  application:
    name: article-service

server:
  port: 13456

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      aigc-service:
        connect-timeout: 10000
        read-timeout: 10000
      default:
        connect-timeout: 3000
        read-timeout: 3000

article:
  bloomFilter:
    size: 100000
    falseProbability: 0.01
#    org.springframework.cloud.openfeign: trace