spring:
  application:
    name: search-service

  redis:
    host: 8.130.19.151
    port: 16379
    database: 0
    password: rIj12YF23S

  elasticsearch:
    uris: localhost:9200

server:
  port: 14606

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

logging:
  level:
    org.springframework.data.elasticsearch: trace
    org.elasticsearch: trace