spring:
  application:
    name: search-service

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

  redis:
    host: 8.130.19.151
    port: 16379
    database: 0
    password: rIj12YF23S
  redisson:
    client:
      connectionPool:
        minIdleSize: 5
        poolSize: 10

  elasticsearch:
    rest:
      uris: 192.168.10.135:9200


server:
  port: 14606

logging:
  level:
    org.springframework.data.elasticsearch: trace
    org.elasticsearch: trace