spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_white_box
    username: root
    password: 1234

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

  session:
    redis:
      flush-mode: immediate

  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 1460698739@qq.com
    password: jkkssflmezusjhjf
    port: 587
    default-encoding: UTF-8

  application:
    name: user-service

server:
  port: 12345

upload:
  path: /whitebox/src/main/resources/imgs
