spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_white_box
    username: root
    password: 1234

  cloud:
    nacos:
      discovery:
        server-addr: 8.130.19.151:8848

  redis:
    host: 8.130.19.151
    port: 16379
    database: 0
    password: rIj12YF23S

  session:
    redis:
      flush-mode: immediate

  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 1460698739@qq.com
    password: jkkssflmezusjhjf
    port: 587
    default-encoding: UTF-8

  application:
    name: user-service

server:
  port: 12345

upload:
  path: /whitebox/src/main/resources/imgs
